import { execFileSync } from "node:child_process";
import { Client } from "pg";
import { startHttpServer, stopHttpServer } from "./http-server";
import {
  resolveTestDatabaseUrl,
  resolveMaintenanceUrl,
  databaseNameOf,
  assertIsTestDatabase,
  redact,
} from "./test-db-url";

/**
 * Vitest globalSetup — provisions the throwaway test database once per run.
 *
 * Drop → create → `prisma db push` → seed. Dropping first means a run never
 * inherits rows from a previous one, so tests cannot pass because of state a
 * neighbouring test left behind.
 *
 * `prisma db push` rather than `migrate deploy`: the test database is
 * disposable and we want the schema as it exists in schema.prisma right now,
 * not the replayed migration history. Migration correctness is a separate
 * concern from behaviour coverage.
 */
export default async function setup() {
  process.loadEnvFile(".env");

  const testUrl = resolveTestDatabaseUrl();
  const dbName = databaseNameOf(testUrl);
  assertIsTestDatabase(testUrl);

  console.log(`\n[test-db] provisioning ${redact(testUrl)}`);

  await recreateDatabase(testUrl, dbName);
  pushSchema(testUrl);
  await seed(testUrl);

  // Test workers read DATABASE_URL at import time (src/lib/database.ts builds
  // its pg Pool on module load), so it must be set before any test file runs.
  process.env.DATABASE_URL = testUrl;

  console.log("[test-db] ready");

  // The HTTP suite needs a production build, which costs about a minute.
  // It is opt-in so the fast service-level suite stays the default inner loop.
  if (process.env.TEST_HTTP === "1") {
    const baseUrl = await startHttpServer(testUrl);
    process.env.TEST_BASE_URL = baseUrl;
    // Returned teardown runs after the whole suite completes.
    return () => stopHttpServer();
  }
}

async function recreateDatabase(testUrl: string, dbName: string) {
  assertIsTestDatabase(testUrl);
  const admin = new Client({ connectionString: resolveMaintenanceUrl(testUrl) });
  await admin.connect();
  try {
    // FORCE terminates lingering connections from a previous crashed run;
    // without it the DROP blocks indefinitely instead of failing fast.
    await admin.query(`DROP DATABASE IF EXISTS "${dbName}" WITH (FORCE)`);
    await admin.query(`CREATE DATABASE "${dbName}"`);
  } finally {
    await admin.end();
  }
}

function pushSchema(testUrl: string) {
  assertIsTestDatabase(testUrl);
  try {
    execFileSync(
      "npx",
      // `--url` overrides the datasource from prisma.config.ts explicitly.
      // Relying on env precedence would work too, but an explicit flag means
      // the target cannot be changed by an unrelated edit to .env.
      // Prisma 7 removed `--skip-generate`; the client is already generated by
      // the postinstall hook.
      ["prisma", "db", "push", "--accept-data-loss", "--url", testUrl],
      {
        env: { ...process.env, DATABASE_URL: testUrl },
        stdio: "pipe",
        shell: process.platform === "win32",
      }
    );
  } catch (error: any) {
    // execFileSync errors serialise as raw byte arrays, which are unreadable
    // in Vitest output. Surface the actual CLI message instead.
    const stderr = error?.stderr?.toString?.() ?? "";
    const stdout = error?.stdout?.toString?.() ?? "";
    throw new Error(`prisma db push failed:
${stderr || stdout || error?.message}`);
  }
}

async function seed(testUrl: string) {
  assertIsTestDatabase(testUrl);
  process.env.DATABASE_URL = testUrl;
  const { seedTestData } = await import("../fixtures/seed");
  await seedTestData();
}
